server:
  port: 8098
spring:
  application:
    name: nacos-consumer
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.93.132:8099
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true